### ISSUE TITLE
Width and height would be undefined for audio tracks, right?

### ISSUE THREAD

**Issue by donato** [gliese1337/HLS.js#6]
Hi @gliese1337, thank you for sharing your work, I've been looking into your mp4 muxing strategy as a reference and had a question. 

When this bit of code is ran for an audio track, I imagine we are writing dummy data into width and height for the trak section.
https://github.com/gliese1337/HLS.js/blob/master/src/MP4Muxer.js#L437

Is this correct?

**Comment by gliese1337** [comment]
That is correct. Width and height are undefined for audio, and undefined gets cast to the integer 0 on bitwise operations, so that just ends up writing zeroes.
Implicitly casting undefined like that is kinda nasty, though; the code would be improved by either explicitly setting the width and height properties for audio tracks to 0, or switching on the track type like we're doing just a few lines earlier anyway.
