### ISSUE TITLE
Is it possible to calculate audio duration?

### ISSUE THREAD

**Issue by donato** [gliese1337/HLS.js#8]
Hey @gliese1337 - sorry to bug you, this project has been a great resource for me!

I am curious if it is possible to calculate the "duration" for an AAC stream instead of relying on it being calculated by the video demuxer and passed in.

https://github.com/gliese1337/HLS.js/blob/master/src/worker.js#L174

This isn't exactly related to your project but I am interested in demuxing an AAC stream from TS and boxing it into an fmp4, and this came up.

**Comment by gliese1337** [comment]
@donato I do not in the least mind being bugged! It's nice to have other people looking this over and helping make it better, even if only by bugging me to give me more motivation to make it better!

In theory, there are two ways that we could calculate the stream length. The first is to look at the presentation time stamps (PTSs) for each TS packet that contains AAC data, subtract the minimum from the maximum, and re-scale for the MPEG-TS clock (basically, divide by 90,000 to get seconds). That's what I used to do, but it turned out to not be sufficiently accurate.

The other thing you could do is count the durations for each audio sample. If you convert the sampling frequency index into an actual sample rate (there's a table lookup for that), then dividing the total number of samples by the sampling frequency should give you the total duration. I'm not sure if I actually tried that out; I think that method ended up producing slight discrepancies with the length of the video, but I could be wrong, so maybe that's worth checking out. Right now, I'm producing MP4s with a single fixed audio sample rate (extracted from the first AAC header in each stream chunk), and that seems to be working just fine with everything I've tested so fat, but in theory every AAC packet could have a separate sample rate, so for maximal compatibility / guaranteed accuracy, you'd probably want to examine every header and accumulate the duration of the audio stream one AAC packet at a time.

**Comment by gliese1337** [comment]
@donato I just pushed a commit (https://github.com/gliese1337/HLS.js/commit/704dcf4ed61699c13f305ec5cfda1a0035ea9497) which calculates the audio duration directly instead of referencing the video. There are some minor (+/- a couple hundredths of a second) discrepancies with the video durations, so this may still need some revision, but everything seems to still be working... so I guess it's close enough for now.

**Comment by donato** [comment]
@gliese1337 - thanks for the detailed response and the extra commit - truly stellar!

I've been off of HLS recently to focus on testing/hardening the next JW release, but I will be returning to this soon.

It is true that sometimes the audio and video will have different durations - it is also true that sometimes they will have different start times. We once had to deal with a transcoder which would put audio files in with negative offset times, doh!
