### ISSUE TITLE
Why mux AAC into mp4?

### ISSUE THREAD

**Issue by donato** [gliese1337/HLS.js#9]
Hey @gliese1337, I just realized we can push aac directly into the video tag - is there a benefit to muxing it into mp4 first?
I imagine it may work better for synchronization, but I'm curious if you've considered this already.

**Comment by gliese1337** [comment]
It keeps the code simpler. Partly, that's because it's better for synchronization (I have to exactly 0 lines of code to maintain synchronization if I make the browser do it instead by putting audio and video in a single package), and partly it's because then I only have to deal with one media element instead of two, which means less code even without considering synchronization.

There may be some benefit to keeping the video and audio channels separate when switching to MSE-based playback, but even then it will still be necessary to package the AAC audio into an MP4 container for compatibility with the MSE API.

**Comment by donato** [comment]
Got it, thanks for the details. It sounds like a trade-off in complexity of the MSE interface versus complexity of the transmuxer. The browser should allow you to use two SourceBuffers with single MediaSource, it's just a question of how well it does so!

I am curious of how the browser will handle the synchronization so I think I'll try it out separately once I get my h264 properly muxed :)
